export const Questions = [
    {
        prompt: 'What is the name of Apple company founder',
        optionA: 'Steve Jobs',
        optionB: 'Steven Hawkins',
        optionC: 'Alen Walker',
        optionD: 'Steve Wonder',
        answer: 'A',
        result: 'Steve Jobs',
    },
    {
        prompt: 'What is the name of the latest missile Nasa launched?',
        optionA: 'Apollo 11',
        optionB: 'Falcon Heavy',
        optionC: 'Artemis 1',
        optionD: 'Challenger',
        answer: 'C',
        result: 'Artemis 1',
    },
    {
        prompt: 'How long is an Olympic swimming pool (in meters)?',
        optionA: '50 meters',
        optionB: '70 meters',
        optionC: '90 meters',
        optionD: '110 meters',
        answer: 'A',
        result: '50 meters',
    },
    {
        prompt: 'Demolition of the Berlin wall separating East and West Germany began in what year?',
        optionA: '1985',
        optionB: '1979',
        optionC: '1989',
        optionD: '1983',
        answer: 'C',
        result: '1989',
    },
    {
        prompt: 'What is the name of the biggest technology company in South Korea?',
        optionA: 'Apple',
        optionB: 'Samsung',
        optionC: 'Motorola',
        optionD: 'Xiaomi',
        answer: 'B',
        result: 'Samsung',
    },
    {
        prompt: 'What is "cynophobia"?',
        optionA: 'Fear of flies',
        optionB: 'Fear of dogs',
        optionC: 'Fear of Ship',
        optionD: 'Fear of cats',
        answer: 'B',
        result: 'Fear of dogs',
    },
    {
        prompt: 'In the state of Georgia, it’s illegal to eat what with a fork?',
        optionA: 'Pizza',
        optionB: 'Sushi',
        optionC: 'Fried Chicken',
        optionD: 'Ravioly',
        answer: 'C',
        result: 'Fried Chicken',
    },
    {
        prompt: 'How long is New Zealand’s Ninety Mile Beach?',
        optionA: '80 miles',
        optionB: '45 miles',
        optionC: '90 miles',
        optionD: '55 miles',
        answer: 'D',
        result: '55 miles',
    },
    {
        prompt: 'How many teeth does an adult human have?',
        optionA: '28',
        optionB: '44',
        optionC: '32',
        optionD: '30',
        answer: 'C',
        result: '32',
    },
    {
        prompt: 'What is the nearest planet to the sun?',
        optionA: 'Marcury',
        optionB: 'Pluto',
        optionC: 'Mars',
        optionD: 'Earth',
        answer: 'A',
        result: 'Marcury',
    },
    {
        prompt: 'What is a single strand of spaghetti called?',
        optionA: 'Spaget',
        optionB: 'Spaghetto',
        optionC: 'Osparg',
        optionD: 'Spagan',
        answer: 'B',
        result: 'Spaghetto',
    },
    {
        prompt: 'Where did the 2000 Summer Olympics take place?',
        optionA: 'Sydney',
        optionB: 'Tokyo',
        optionC: 'Baharein',
        optionD: 'Monaco',
        answer: 'A',
        result: 'Sydney',
    },
    {
        prompt: 'What is an eight-sided shape called?',
        optionA: 'Optagon',
        optionB: 'Getagon',
        optionC: 'Octagon',
        optionD: 'Ochotagon',
        answer: 'C',
        result: 'Octagon',
    },
    {
        prompt: 'Hg is the chemical symbol of which element?',
        optionA: 'Zink',
        optionB: 'Iron',
        optionC: 'Neodium',
        optionD: 'Mercury',
        answer: 'D',
        result: 'Mercury',
    },
    {
        prompt: 'What is the capital city of Spain?',
        optionA: 'Missisippi',
        optionB: 'Shanghi',
        optionC: 'San Leon',
        optionD: 'Madrid',
        answer: 'D',
        result: 'Madrid',
    },
    {
        prompt: 'Globe and Jerusalem are types of what? ',
        optionA: 'Orenge',
        optionB: 'Artichokes',
        optionC: 'Cities',
        optionD: 'Violines',
        answer: 'B',
        result: 'Artichokes',
    },
    {
        prompt: 'Pure water has a pH level of around?',
        optionA: 'Four',
        optionB: 'Seven',
        optionC: 'Three',
        optionD: 'Six',
        answer: 'B',
        result: 'Seven',
    },
    {
        prompt: 'How long does it take to hard boil an egg? ',
        optionA: '7 minutes',
        optionB: '4 minutes',
        optionC: '11 minutes',
        optionD: '6 minutes',
        answer: 'A',
        result: '7 minutes',
    },
    {
        prompt: 'What did the Crocodile swallow in Peter Pan? ',
        optionA: 'A kid',
        optionB: 'A table',
        optionC: 'A watermelon',
        optionD: 'An Alarm Clock',
        answer: 'D',
        result: 'An Alarm Clock',
    },
    {
        prompt: 'Which country is Prague in?',
        optionA: 'Czech Republic',
        optionB: 'Madrid',
        optionC: 'Paris',
        optionD: 'London',
        answer: 'A',
        result: 'Czech Republic',
    },
    {
        prompt: 'What is the capital city of France? ',
        optionA: 'Toulouse',
        optionB: 'Marseille',
        optionC: 'Nice',
        optionD: 'Paris',
        answer: 'D',
        result: 'Paris',
    },
    {
        prompt: 'Who was the first person to walk on the moon?',
        optionA: 'John Glenn',
        optionB: 'Neil Armstrong',
        optionC: 'Buzz Aldrin',
        optionD: 'Alan Shepard',
        answer: 'B',
        result: 'Neil Armstrong',
    },
    {
        prompt: 'In what year did the United States declare its independence from Great Britain? ',
        optionA: '1776',
        optionB: '1692',
        optionC: '1808',
        optionD: '1922',
        answer: 'A',
        result: '1776',
    },
    {
        prompt: 'What is the largest ocean on Earth? ',
        optionA: 'Atlantic Ocean',
        optionB: 'Indian Ocean',
        optionC: 'Pacific Ocean',
        optionD: 'Arctic Ocean',
        answer: 'C',
        result: 'Pacific Ocean',
    },
    {
        prompt: 'Who wrote the novel "War and Peace"?',
        optionA: 'Leo Tolstoy',
        optionB: 'Ernest Hemingway',
        optionC: 'Jane Austen',
        optionD: 'William Shakespeare',
        answer: 'A',
        result: 'Leo Tolstoy',
    },
    {
        prompt: 'In what year was the novel "War and Peace" published ?',
        optionA: '1805',
        optionB: '1812',
        optionC: '1869',
        optionD: '1887',
        answer: 'C',
        result: '1869',
    },
    {
        prompt: 'How many volumes does "War and Peace" consist of?',
        optionA: '1',
        optionB: '2',
        optionC: '3',
        optionD: '4',
        answer: 'D',
        result: '4',
    },
    {
        prompt: 'What is the nationality of the author of "War and Peace"?',
        optionA: 'American',
        optionB: 'British',
        optionC: 'French',
        optionD: 'Russian',
        answer: 'D',
        result: 'Russian',
    },
    {
        prompt: 'What is the name of the desert planet where the original Star Wars trilogy begins?',
        optionA: 'Hoth',
        optionB: 'Tatooine',
        optionC: 'Endor',
        optionD: 'Alderaan',
        answer: 'B',
        result: 'Tatooine',
    },
    {
        prompt: 'Who is the protagonist of the Star Wars prequel trilogy?',
        optionA: 'Obi - Wan Kenobi',
        optionB: 'Yoda',
        optionC: 'Anakin Skywalker',
        optionD: 'Mace Windu',
        answer: 'C',
        result: 'Anakin Skywalker',
    },
    {
        prompt: 'Who is the main villain in the original Star Wars trilogy?',
        optionA: 'Jabba the Hutt',
        optionB: 'Darth Vader',
        optionC: 'Emperor Palpatine',
        optionD: 'Boba Fett',
        answer: 'B',
        result: 'Darth Vader',
    },
    {
        prompt: 'In which book of the Harry Potter series does Harry Potter first learn that he is a wizard?',
        optionA: 'The Chamber of Secrets',
        optionB: 'The Prisoner of Azkaban',
        optionC: 'The Philosophers Stone',
        optionD: 'The Goblet of Fire',
        answer: 'C',
        result: 'The Philosophers Stone',
    },
    {
        prompt: 'Who is the headmaster of Hogwarts School of Witchcraft and Wizardry at the start of the Harry Potter series?',
        optionA: 'Albus Dumbledore',
        optionB: 'Gilderoy Lockhart',
        optionC: 'Severus Snape',
        optionD: 'Rubeus Hagrid',
        answer: 'A',
        result: 'Albus Dumbledore',
    },
    {
        prompt: 'What is the name of the Hogwarts School of Witchcraft and Wizardrys sports team?',
        optionA: 'The Gryffindor Lions',
        optionB: 'The Hufflepuff Badgers',
        optionC: 'The Ravenclaw Eagles',
        optionD: 'The Slytherin Snakes',
        answer: 'D',
        result: 'The Slytherin Snakes',
    },
    {
        prompt: 'Who is the author of the Harry Potter series of books?',
        optionA: 'J.K. Rowling',
        optionB: 'J.R.R. Tolkien',
        optionC: 'J.M. Barrie',
        optionD: 'L. Frank Baum',
        answer: 'A',
        result: 'J.K. Rowling',
    },
    {
        prompt: 'Who is the half-blood prince mentioned in the title of the sixth book in the Harry Potter series?',
        optionA: 'Albus Dumbledore',
        optionB: 'Severus Snape',
        optionC: 'Harry Potter',
        optionD: 'Ron Weasley',
        answer: 'B',
        result: 'Severus Snape',
    },
    {
        prompt: 'What is the most prestigious race in the Formula 1 World Championship?',
        optionA: 'The Monaco Grand Prix',
        optionB: 'The Australian Grand Prix',
        optionC: 'The Canadian Grand Prix',
        optionD: 'The British Grand Prix',
        answer: 'A',
        result: 'The Monaco Grand Prix',
    },
    {
        prompt: 'Who is the most successful driver in the history of Formula 1 in terms of race wins?',
        optionA: 'Michael Schumacher',
        optionB: 'Ayrton Senna',
        optionC: 'Lewis Hamilton',
        optionD: 'Alain Prost',
        answer: 'A',
        result: 'Michael Schumacher',
    },
    {
        prompt: 'What is the name of the Formula 1 governing body?',
        optionA: 'FIA',
        optionB: 'F1',
        optionC: 'FOA',
        optionD: 'FOM',
        answer: 'A',
        result: 'FIA',
    },
    {
        prompt: 'How many points is a driver awarded for winning a Formula 1 race?',
        optionA: '10',
        optionB: '25',
        optionC: '50',
        optionD: '100',
        answer: 'B',
        result: '25',
    },
    {
        prompt: 'Who is the most successful team in the history of Formula 1 in terms of constructors championships?',
        optionA: 'Mercedes',
        optionB: 'Ferrari',
        optionC: 'McLaren',
        optionD: 'Red Bull Racing',
        answer: 'B',
        result: 'Ferrari',
    },
    {
        prompt: 'What is the name of Joeys stuffed penguin toy?',
        optionA: 'Hugsy',
        optionB: 'Puddles',
        optionC: 'Snuggles',
        optionD: 'Fluffy',
        answer: 'A',
        result: 'Hugsy',
    },
    {
        prompt: 'Who is the mother of Rosss son Ben?',
        optionA: 'Carol',
        optionB: 'Rachel',
        optionC: 'Emily',
        optionD: 'Mona',
        answer: 'A',
        result: 'Carol',
    },
    {
        prompt: 'What is the name of Joeys agent?',
        optionA: 'Estelle',
        optionB: 'Lois',
        optionC: 'Jane',
        optionD: 'Judy',
        answer: 'A',
        result: 'Estelle',
    },
    {
        prompt: 'What is the name of the coffee shop where the friends often hang out?',
        optionA: 'Central Perk',
        optionB: 'The Bean',
        optionC: 'Java Junction',
        optionD: 'Coffeehouse',
        answer: 'A',
        result: 'Central Perk',
    },
    {
        prompt: 'What is the name of the character played by Jennifer Aniston?',
        optionA: 'Monica',
        optionB: 'Phoebe',
        optionC: 'Rachel',
        optionD: 'Ross',
        answer: 'C',
        result: 'Rachel',
    },
];
